build(deps-dev): bump io.rest-assured:rest-assured from 5.4.0 to 5.5.0 (#71)
Bumps
[io.rest-assured:rest-assured](https://github.com/rest-assured/rest-assured)
from 5.4.0 to 5.5.0.
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/rest-assured/rest-assured/blob/master/changelog.txt">io.rest-assured:rest-assured's
changelog</a>.</em></p>
<blockquote>
<h2>Changelog 5.5.0 (2024-07-05)</h2>
<ul>
<li>
<p>Removing custom validation of pathParams in the mock-mvc module and
instead rely on the Spring implementation(issue 1782) (thanks to
taeyeon-Kim for pull request)</p>
</li>
<li>
<p>Fixing &quot;Error java.lang.NoSuchMethodError for
HttpMethod.resolve()&quot; in mock-mvc module (issue 1760) (thanks to
d0vi for pull request)</p>
</li>
<li>
<p>Fix <a
href="https://redirect.github.com/rest-assured/rest-assured/issues/1707">#1707</a>:
SVG file upload - fatal error :1:1: content is not allowed in prolog (<a
href="https://redirect.github.com/rest-assured/rest-assured/issues/1777">#1777</a>)
(thanks to Byounghee kim for pull request)</p>
</li>
<li>
<p>Fix <a
href="https://redirect.github.com/rest-assured/rest-assured/issues/1773">#1773</a>:
Remove check for response HTTP status code. (thanks to macmon for pull
request)</p>
</li>
<li>
<p>Introducing the &quot;scala-extensions&quot; module for Scala 3 (<a
href="https://redirect.github.com/rest-assured/rest-assured/issues/1770">#1770</a>).
This means that you can write tests like this in Scala 3:</p>
<p><a href="https://github.com/Test"><code>@​Test</code></a>
def <code>extraction with rest assured scala extensions</code>: Unit =
val message: String = Given(req =&gt;
req.port(7000)
req.header(&quot;Header&quot;, &quot;Header&quot;)
req.body(&quot;hello&quot;)
)
.When(
_.put(&quot;/the/path&quot;)
)
.Extract(
_.path(&quot;message&quot;)
)
assertThat(message).isEqualTo(&quot;Hello World&quot;)
(thanks to Carlos Eduardo for pull request)</p>
</li>
<li>
<p>Remove deprecated Content-Transfer-Encoding from multipart post
headers (<a
href="https://redirect.github.com/rest-assured/rest-assured/issues/1762">#1762</a>)
(thanks to Michal Trna for pull request)</p>
</li>
<li>
<p>Fixed pathParams double encoding in mock-mvd module (<a
href="https://redirect.github.com/rest-assured/rest-assured/issues/1756">#1756</a>)
(thanks to Dmitry Kaukov for pull request)</p>
</li>
<li>
<p>Upgraded Groovy from version 4.0.16 to 4.0.22</p>
</li>
<li>
<p>Upgraded Jackson from version 2.14.3 to 2.17.1</p>
</li>
<li>
<p>Upgraded kotlin extension module to use Kotlin 2.0.0 (previously
1.9.20 was used)</p>
</li>
<li>
<p>Upgraded Guava library from 32.0.1-jre to 33.2.1-jre</p>
</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/rest-assured/rest-assured/commit/bea603cb81ebe0fd1a2fda325f7d470064349470"><code>bea603c</code></a>
[maven-release-plugin] prepare release rest-assured-5.5.0</li>
<li><a
href="https://github.com/rest-assured/rest-assured/commit/401174acba34530a5cc642b31d4ecb30f2eb676c"><code>401174a</code></a>
Added workaround for scala maven plugin javadoc generation</li>
<li><a
href="https://github.com/rest-assured/rest-assured/commit/08cf7c22ec7a7ff2d2ad39931ff5d6457e758fd3"><code>08cf7c2</code></a>
Trying to generate javadoc for scala-extensions</li>
<li><a
href="https://github.com/rest-assured/rest-assured/commit/b82693f96e694b24567be88e3a52321fe683ff2d"><code>b82693f</code></a>
Upgraded sundr-maven-plugin to 0.103.1</li>
<li><a
href="https://github.com/rest-assured/rest-assured/commit/e24d68f689340e8db8852dad46d8b85b8c4d5129"><code>e24d68f</code></a>
Revert &quot;Upgraded sundr-maven-plugin to 0.200.0&quot;</li>
<li><a
href="https://github.com/rest-assured/rest-assured/commit/6d913c0694137097d902b254e9946959b166bd9e"><code>6d913c0</code></a>
[ci skip] Preparing changelog for release</li>
<li><a
href="https://github.com/rest-assured/rest-assured/commit/df51fb88a88ffa7bec8766a9b6e0df9329e0b2a1"><code>df51fb8</code></a>
Upgraded sundr-maven-plugin to 0.200.0</li>
<li><a
href="https://github.com/rest-assured/rest-assured/commit/2b5077710ab08ace5758444aa88c67bfcaa3e6eb"><code>2b50777</code></a>
Upgraded Jackson from version 2.14.3 to 2.17.1</li>
<li><a
href="https://github.com/rest-assured/rest-assured/commit/511cc3488091be55806f3fce23241bd632197e77"><code>511cc34</code></a>
Upgraded Guava library from 32.0.1-jre to 33.2.1-jre</li>
<li><a
href="https://github.com/rest-assured/rest-assured/commit/d7c065d8a7b22f9067552776cf6dd2f9af9f3284"><code>d7c065d</code></a>
Upgraded dokka to 1.9.20</li>
<li>Additional commits viewable in <a
href="https://github.com/rest-assured/rest-assured/compare/rest-assured-5.4.0...rest-assured-5.5.0">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=io.rest-assured:rest-assured&package-manager=maven&previous-version=5.4.0&new-version=5.5.0)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>